# Generated by Django 3.2.6 on 2021-08-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210805_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownpatients',
            old_name='patient',
            new_name='patients',
        ),
        migrations.RenameField(
            model_name='pastpatients',
            old_name='patient',
            new_name='patients',
        ),
    ]
