# Generated by Django 3.2.6 on 2021-08-04 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patientsinfo_remark'),
        ('users', '0007_auto_20210805_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patients', models.ManyToManyField(to='patients.PatientsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PastPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patients', models.ManyToManyField(to='patients.PatientsInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='pastpatients',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='pastpatients',
            name='patients',
        ),
        migrations.DeleteModel(
            name='OwnPatients',
        ),
        migrations.DeleteModel(
            name='PastPatients',
        ),
    ]
