version: '3.7'
services:
  tcm_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volume:
      - static:/static
    ports:
      - "8000:80"
    depends_on:
      - tcm_gunicorn

volumes:
  static:
