from django.db import models
from patients.models import DiagnosisRecord

class Acupuncture(models.Model):
    '''
    - AcupunctureID VARCHAR(50) <pk> auto-generated by Django
	- AcupunctureName VARCHAR(50)
    - AcupunctureArea VARCHAR(50)
    - AcupunctureInfo TEXT
    '''
    
    class Meta:
        db_table = 'Acupuncture'
        ordering = ['-name',]
    
    name = models.CharField(max_length=64, blank=True, null=True)
    area = models.CharField(max_length=64, blank=True, null=True)
    info = models.TextField(blank=True, null=True)


class AcupunctureRecord(models.Model):
    '''
    - AcupunctureRecordID VARCHAR(50) <pk> auto-generated by Django
    - AcupunctureID VARCHAR(50) <fk>
    - DiagnosisRecordID VARCHAR(50) <fk>
    - AcupunctureRecordTime VARCHAR(50)
    '''

    class Meta:
        db_table = 'AcupunctureRecord'
        ordering = ['-acupuncture_record_time',]
    
    acupuncture_id = models.ForeignKey(
        Acupuncture,
        related_name='acupuncture_rec',
        on_delete=models.CASCADE)
    diagnosis_record_id = models.ForeignKey(
        DiagnosisRecord,
        related_name='acupuncture_rec',
        on_delete=models.CASCADE)
    acupuncture_record_time = models.CharField(max_length=64, blank=True, null=True)