# Generated by Django 4.0.2 on 2022-02-13 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('data', models.JSONField()),
                ('remarks', models.CharField(max_length=256)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
