# Generated by Django 3.2.9 on 2021-12-04 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulse',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
