# Generated by Django 4.0.2 on 2022-03-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PulseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'PulseOption',
                'verbose_name_plural': 'PulseOptions',
            },
        ),
        migrations.CreateModel(
            name='WangOptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'WangOptionCategory',
                'verbose_name_plural': 'WangOptionCategories',
            },
        ),
        migrations.CreateModel(
            name='WenOptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'WenOptionCategory',
                'verbose_name_plural': 'WenOptionCategories',
            },
        ),
        migrations.CreateModel(
            name='WenOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wen_category', to='option.wenoptioncategory')),
            ],
            options={
                'verbose_name': 'WenOptionCategory',
                'verbose_name_plural': 'WenOptionCategories',
            },
        ),
        migrations.CreateModel(
            name='WangOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wang_category', to='option.wangoptioncategory')),
            ],
            options={
                'verbose_name': 'WangOption',
                'verbose_name_plural': 'WangOptions',
            },
        ),
    ]
