# Generated by Django 4.0.2 on 2022-03-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseOptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'DiseaseCategory',
                'verbose_name_plural': 'DiseaseCategories',
            },
        ),
        migrations.CreateModel(
            name='DiseaseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_category', to='option.diseaseoptioncategory')),
            ],
            options={
                'verbose_name': 'DiseaseOption',
                'verbose_name_plural': 'DiseaseOptions',
            },
        ),
    ]
