# Generated by Django 4.0.3 on 2022-04-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_diseaseoptioncategory_diseaseoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'EyeCategory',
                'verbose_name_plural': 'EyeCategories',
                'db_table': 'EyeCategory',
            },
        ),
        migrations.CreateModel(
            name='TongueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'TongueCategory',
                'verbose_name_plural': 'TongueCategories',
                'db_table': 'TongueCategory',
            },
        ),
        migrations.CreateModel(
            name='TongueOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tongue_category', to='option.eyecategory')),
            ],
            options={
                'verbose_name': 'TongueOption',
                'verbose_name_plural': 'TongueOptions',
                'db_table': 'TongueOption',
            },
        ),
        migrations.CreateModel(
            name='EyeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_category', to='option.eyecategory')),
            ],
            options={
                'verbose_name': 'EyeOption',
                'verbose_name_plural': 'EyeOptions',
                'db_table': 'EyeOption',
            },
        ),
    ]
