# Generated by Django 4.0.3 on 2022-04-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0003_eyecategory_tonguecategory_tongueoption_eyeoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tongueoption',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tongue_category', to='option.tonguecategory'),
        ),
    ]
