# Generated by Django 4.0.2 on 2022-02-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('ch_name', models.CharField(max_length=255)),
                ('en_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Diseases',
                'ordering': ['code'],
            },
        ),
    ]
