# Generated by Django 3.2.9 on 2021-12-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseases',
            options={'ordering': ['code'], 'verbose_name_plural': 'Diseases'},
        ),
    ]
