from django.db import models
from acupuncture.models import Acupuncture
from patients.models import DiagnosisRecord

class Medicine(models.Model):
    '''
    MedcineID VARCHAR(50) <pk> auto-generated by Django
    MedcineName VARCHAR(20)
    MedcineType VARCHAR(10)
    MedcineBopomoCode VARCHAR(20)
    MedcineNHIID VARCHAR(20)
    MedcineNHIName VARCHAR(20)
    MedcineCost FLOAT8
    MedcinePrice FLOAT8
    MedcineInfo TEXT
    '''

    class Meta:
        db_table = 'Medcine'
        ordering = ['-bopomofo', '-name',]
    
    name = models.CharField(max_length=20)
    type = models.CharField(max_length=10, blank=True, null=True)
    bopomofo = models.CharField(max_length=20)
    nhi_id = models.CharField(max_length=20, blank=True, null=True)
    nhi_name = models.CharField(max_length=20, blank=True, null=True)
    manufacturer = models.CharField(max_length=20, blank=True, null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    info = models.TextField(blank=True, null=True)


class MedicineRecord(models.Model):
    '''
    MedicineRecordID VARCHAR(50) <pk> auto-generated by Django
    MedicineID  VARCHAR(50) <fk>
    DiagnosisRecordID  VARCHAR(50) <fk>
    MedicineDosage FLOAT8
    MedicineSubTotal FLOAT8
    '''

    class Meta:
        db_table = 'MedcineRecord'
        ordering = ['-subtotal',]
    
    medicine_id = models.ForeignKey(
        Medicine,
        related_name='medcine_rec',
        on_delete=models.CASCADE)
    diagnosis_record_id = models.ForeignKey(
        DiagnosisRecord,
        related_name='medcine_rec',
        on_delete=models.CASCADE)
    dosage = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=0)


class Decoction(models.Model):
    name = models.CharField(max_length=10, blank=True, null=True)
    bopomofo = models.CharField(max_length=20)
    cost = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    info = models.TextField(blank=True, null=True)


class DecoctionComponents(models.Model):
    decoction_id = models.ForeignKey(
        Decoction,
        related_name='decoc_component',
        on_delete=models.CASCADE)
    medicine_id = models.ForeignKey(
        Medicine,
        related_name='decoc_component',
        on_delete=models.CASCADE)
    dosage = models.DecimalField(max_digits=10, decimal_places=2, default=0)


class DecoctionRecord(models.Model):
    decoction_id = models.ForeignKey(
        Decoction,
        related_name='decoc_rec',
        on_delete=models.CASCADE)
    diagnosis_record_id = models.ForeignKey(
        DiagnosisRecord,
        related_name='decoc_rec',
        on_delete=models.CASCADE)
    dosage = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=0)