# Generated by Django 4.0.2 on 2022-02-13 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_history', models.CharField(blank=True, max_length=256, null=True)),
                ('main_complaint', models.TextField(blank=True, null=True)),
                ('pulse', models.TextField(blank=True, null=True)),
                ('disease_name', models.CharField(blank=True, max_length=50, null=True)),
                ('med_pack_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('med_day', models.SmallIntegerField()),
                ('med_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_rec', to=settings.AUTH_USER_MODEL)),
                ('employee_work_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_rec', to='users.employeeworkschedule')),
            ],
            options={
                'db_table': 'DiagnosisRecord',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1)),
                ('birthday', models.DateField()),
                ('nhi_card_num', models.CharField(blank=True, max_length=20, null=True)),
                ('id_num', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.DecimalField(decimal_places=3, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('blood_type', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=10, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('emergency_contact_rel', models.CharField(blank=True, max_length=10, null=True)),
                ('job', models.CharField(blank=True, max_length=10, null=True)),
                ('edu_level', models.CharField(blank=True, max_length=10, null=True)),
                ('marriage', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'db_table': 'Patient',
                'ordering': ['-name', '-birthday'],
            },
        ),
        migrations.CreateModel(
            name='TongueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/tongue')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagnosis_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tongue_img', to='patients.diagnosisrecord')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tongue_img', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'TongueImages',
                'db_table': 'TongueImage',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientRegisterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_register_rec', to='patients.patient')),
            ],
            options={
                'db_table': 'PatientRegisterRecord',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='EyeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/eye')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagnosis_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_img', to='patients.diagnosisrecord')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_img', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'EyeImages',
                'db_table': 'EyeImage',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_rec', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='patient_register_record_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_rec', to='patients.patientregisterrecord'),
        ),
    ]
