# Generated by Django 3.2.7 on 2021-09-08 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1)),
                ('arrears', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_id', models.CharField(max_length=200)),
                ('consultation_no', models.IntegerField()),
                ('department', models.CharField(max_length=200)),
                ('medical_order_number', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('period', models.IntegerField()),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisInfo',
            fields=[
                ('patientsinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patients.patientsinfo')),
                ('diagnosis_data', models.JSONField(default=dict)),
                ('gan_img', models.ImageField(default='default.jpg', upload_to='gan')),
                ('she_img', models.ImageField(default='default.jpg', upload_to='she')),
            ],
            bases=('patients.patientsinfo',),
        ),
    ]
