# Generated by Django 4.0.2 on 2022-03-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestVid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.FileField(upload_to='videos/%Y/%m')),
            ],
            options={
                'verbose_name_plural': 'TestVids',
                'db_table': 'TestVid',
            },
        ),
        migrations.AlterField(
            model_name='eyeimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/eye/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='tongueimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/tongue/%Y/%m'),
        ),
    ]
