# Generated by Django 3.2.6 on 2021-08-04 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsinfo',
            old_name='insurance_type',
            new_name='card_id',
        ),
        migrations.RenameField(
            model_name='patientsinfo',
            old_name='medical_record_number',
            new_name='consultation_no',
        ),
        migrations.RemoveField(
            model_name='patientsinfo',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='arrears',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='department',
            field=models.CharField(default='s', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='medical_order_number',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='path',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='period',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='register_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='remark',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='status',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1),
        ),
    ]
