# Generated by Django 3.2.7 on 2021-09-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisinfo',
            name='gan_img',
            field=models.ImageField(default='default.jpg', upload_to='yan'),
        ),
    ]
