# Generated by Django 3.2.7 on 2021-09-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheimages',
            old_name='dianosis',
            new_name='diagnosis',
        ),
    ]
