# Generated by Django 4.0.3 on 2022-04-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_testvid_alter_eyeimage_image_alter_tongueimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestVid',
        ),
        migrations.RemoveField(
            model_name='eyeimage',
            name='diagnosis_record_id',
        ),
        migrations.RemoveField(
            model_name='tongueimage',
            name='diagnosis_record_id',
        ),
        migrations.AddField(
            model_name='eyeimage',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tongueimage',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eyeimage',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientId', to='patients.patient'),
        ),
    ]
