# Generated by Django 3.2.6 on 2021-08-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210804_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
