# Generated by Django 4.0.3 on 2022-04-10 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_delete_testvid_remove_eyeimage_diagnosis_record_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='videos/%Y/%m')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_media', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'OtherMedia',
                'db_table': 'OtherMedia',
            },
        ),
    ]
