# Generated by Django 3.2.6 on 2021-08-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientsinfo_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
