# Generated by Django 3.2.7 on 2021-10-03 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_dianosis_yanimages_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheimages',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sheimages',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='yanimages',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='yanimages',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
