# Generated by Django 3.2.9 on 2021-12-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20211003_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisinfo',
            name='diagnosis_desc',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisinfo',
            name='medical_history',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='diagnosisinfo',
            name='physique',
            field=models.JSONField(default=dict),
        ),
    ]
