# Generated by Django 4.0.2 on 2022-02-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('bopomofo', models.CharField(max_length=20)),
                ('nhi_id', models.CharField(blank=True, max_length=20, null=True)),
                ('nhi_name', models.CharField(blank=True, max_length=20, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Medcine',
                'ordering': ['-bopomofo', '-name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diagnosis_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medcine_rec', to='patients.diagnosisrecord')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medcine_rec', to='medicines.medicine')),
            ],
            options={
                'db_table': 'MedcineRecord',
                'ordering': ['-subtotal'],
            },
        ),
    ]
