# Generated by Django 3.2.8 on 2021-10-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bapomofo', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=256)),
                ('info', models.JSONField(default=dict)),
            ],
        ),
    ]
