# Generated by Django 3.2.9 on 2022-06-16 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20220616_2119'),
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('bopomofo', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecoctionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('decoction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoc_rec', to='medicines.decoction')),
                ('diagnosis_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoc_rec', to='patients.diagnosisrecord')),
            ],
        ),
        migrations.CreateModel(
            name='DecoctionComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('decoction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoc_component', to='medicines.decoction')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoc_component', to='medicines.medicine')),
            ],
        ),
    ]
