# Generated by Django 3.2.9 on 2021-12-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YaoMedicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bapomofo', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=256)),
                ('info', models.JSONField(default=dict)),
            ],
        ),
        migrations.RenameModel(
            old_name='Medicines',
            new_name='FangMedicines',
        ),
    ]
