# Generated by Django 3.2.9 on 2022-06-21 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20220616_2119'),
        ('medicines', '0002_decoction_decoctioncomponents_decoctionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InjuryTreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.SmallIntegerField()),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnosis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_treatment', to='patients.diagnosisrecord')),
                ('injury_treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_treatment', to='medicines.injurytreatment')),
            ],
        ),
    ]
