# Generated by Django 3.2.9 on 2022-06-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_injurytreatment_injurytreatmentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
