# Generated by Django 3.2.9 on 2022-06-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_medicine_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoctioncomponents',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
