# Generated by Django 3.2.9 on 2022-06-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_decoctioncomponents_unit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicine',
            table='Medicine',
        ),
    ]
