# Generated by Django 3.2.9 on 2022-06-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcupunctureArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'AcupunctureArea',
            },
        ),
        migrations.CreateModel(
            name='DongAcupunctureArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'DongAcupunctureArea',
            },
        ),
        migrations.CreateModel(
            name='DongAcupuncture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('link', models.CharField(blank=True, max_length=64, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dongacupuncture', to='acupuncture.dongacupuncturearea')),
            ],
            options={
                'db_table': 'DongAcupuncture',
            },
        ),
        migrations.CreateModel(
            name='Acupuncture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('link', models.CharField(blank=True, max_length=64, null=True)),
                ('alias', models.CharField(blank=True, max_length=64, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acupuncture', to='acupuncture.acupuncturearea')),
            ],
            options={
                'db_table': 'Acupuncture',
            },
        ),
    ]
