# Generated by Django 4.0.2 on 2022-02-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acupuncture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('area', models.CharField(blank=True, max_length=64, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Acupuncture',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='AcupunctureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acupuncture_record_time', models.CharField(blank=True, max_length=64, null=True)),
                ('acupuncture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acupuncture_rec', to='acupuncture.acupuncture')),
                ('diagnosis_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acupuncture_rec', to='patients.diagnosisrecord')),
            ],
            options={
                'db_table': 'AcupunctureRecord',
                'ordering': ['-acupuncture_record_time'],
            },
        ),
    ]
